"use client";

import React, { useState, useRef } from 'react';
import { useAppStore } from '@/lib/store';
import { useAuthStore } from '@/lib/auth-store';
import { toast } from 'sonner';
import { DoorOpen, Plus, Trash2, Clock, CalendarDays, Save, Users, Printer, FileDown, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';

const OPEN_LAB_ID = 3;
const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export default function OpenLabManager() {
  const currentUser = useAuthStore((s) => s.currentUser);
  const openLabSlots = useAppStore((s) => s.openLabSlots);
  const saLabPermissions = useAppStore((s) => s.saLabPermissions);
  const labVisits = useAppStore((s) => s.labVisits);
  const addOpenLabSlot = useAppStore((s) => s.addOpenLabSlot);
  const deleteOpenLabSlot = useAppStore((s) => s.deleteOpenLabSlot);

  const saId = currentUser?.id || '';
  const myPermission = saLabPermissions.find((p) => p.saId === saId);
  const allowedLabs = myPermission?.labIds || [];
  const canManage = allowedLabs.includes(OPEN_LAB_ID);

  const [newDay, setNewDay] = useState('Monday');
  const [newStart, setNewStart] = useState('08:00');
  const [newEnd, setNewEnd] = useState('17:00');
  const [showRecords, setShowRecords] = useState(false);
  const [filterRole, setFilterRole] = useState<string>('all');
  const printRef = useRef<HTMLDivElement>(null);

  const labSlots = openLabSlots.filter((s) => s.labId === OPEN_LAB_ID);
  const allVisits = labVisits.filter((v) => v.labId === OPEN_LAB_ID);
  const activeVisitors = allVisits.filter((v) => !v.leftAt);
  const completedVisits = allVisits.filter((v) => v.leftAt);
  const filteredVisits = filterRole === 'all' ? completedVisits : completedVisits.filter((v) => v.userRole === filterRole);

  const handleAdd = () => {
    if (!canManage) { toast.error('No permission for Lab 3. Ask Admin for access.'); return; }
    if (newStart >= newEnd) { toast.error('Start time must be before end time.'); return; }
    addOpenLabSlot({ labId: OPEN_LAB_ID, day: newDay, startTime: newStart, endTime: newEnd });
    toast.success(`Added ${newDay} ${newStart}–${newEnd} for Lab 3`);
  };

  const handleDelete = (id: string) => {
    if (!canManage) { toast.error('No permission for Lab 3.'); return; }
    deleteOpenLabSlot(id);
    toast.success('Time slot removed.');
  };

  const handlePrint = () => {
    if (!printRef.current) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html><head><title>Open Laboratory 3 — Visitor Records</title>
      <style>
        body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #111; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        p.sub { font-size: 12px; color: #666; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { background: #f3f4f6; text-align: left; padding: 10px 12px; font-weight: 700; text-transform: uppercase; font-size: 10px; letter-spacing: 0.05em; border-bottom: 2px solid #e5e7eb; }
        td { padding: 8px 12px; border-bottom: 1px solid #f3f4f6; }
        tr:hover { background: #fafafa; }
        .footer { margin-top: 40px; font-size: 10px; color: #999; }
      </style></head><body>
      <h1>Open Laboratory 3 — Visitor Records</h1>
      <p class="sub">Printed on ${new Date().toLocaleString()} · ComLab Connect FSUU</p>
      ${printRef.current.innerHTML}
      <p class="footer">Total records: ${filteredVisits.length} · Generated by ComLab Connect</p>
      </body></html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Open Laboratory 3 — Manager</h1>
        <p className="text-sm text-gray-500 mt-1">Manage availability and view visitor records for the Open Laboratory.</p>
      </div>

      {/* Active Visitors */}
      {activeVisitors.length > 0 && (
        <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6 shadow-sm">
          <div className="flex items-center gap-2 mb-4">
            <Users className="h-5 w-5 text-blue-600" />
            <h2 className="text-sm font-bold text-gray-900">Currently Inside ({activeVisitors.length})</h2>
            <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {activeVisitors.map((v) => (
              <div key={v.id} className="flex items-center justify-between bg-white p-4 rounded-xl border border-blue-100 shadow-sm">
                <div>
                  <p className="text-sm font-bold text-gray-900">{v.userName}</p>
                  <p className="text-[10px] text-gray-500 font-medium capitalize">{v.userRole} · Entered {new Date(v.enteredAt).toLocaleTimeString()}</p>
                </div>
                <span className="text-[10px] font-bold text-blue-600 bg-blue-50 px-2 py-1 rounded-full uppercase tracking-widest">Active</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Schedule */}
        <div className="lg:col-span-2 bg-white border border-gray-100 rounded-2xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-2">
              <CalendarDays className="h-5 w-5 text-emerald-600" />
              <h2 className="text-sm font-bold text-gray-900">Lab 3 — Weekly Schedule</h2>
            </div>
            {canManage ? (
              <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full uppercase tracking-widest">Editable</span>
            ) : (
              <span className="text-[10px] font-bold text-gray-400 bg-gray-50 px-2 py-1 rounded-full uppercase tracking-widest">No Permission</span>
            )}
          </div>

          {labSlots.length === 0 ? (
            <div className="text-center py-12">
              <DoorOpen className="h-8 w-8 text-gray-300 mx-auto mb-3" />
              <p className="text-sm text-gray-400 font-medium">No schedule set yet.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {DAYS.map((day) => {
                const daySlots = labSlots.filter((s) => s.day === day);
                if (daySlots.length === 0) return null;
                return (
                  <div key={day} className="flex items-center justify-between p-3 rounded-xl bg-gray-50/80 border border-gray-100">
                    <span className="text-xs font-bold text-gray-700 w-24">{day}</span>
                    <div className="flex items-center gap-3 flex-1 flex-wrap">
                      {daySlots.map((slot) => (
                        <div key={slot.id} className="flex items-center gap-2 bg-white px-3 py-1.5 rounded-lg border border-gray-100 shadow-sm">
                          <Clock className="h-3 w-3 text-gray-400" />
                          <span className="text-xs font-medium text-gray-700">{slot.startTime} — {slot.endTime}</span>
                          {canManage && (
                            <button onClick={() => handleDelete(slot.id)} className="text-gray-300 hover:text-red-500 ml-1">
                              <Trash2 className="h-3 w-3" />
                            </button>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Add slot form */}
        <div className={`bg-white border border-gray-100 rounded-2xl p-6 shadow-sm ${!canManage ? 'opacity-50 pointer-events-none' : ''}`}>
          <div className="flex items-center gap-2 mb-6">
            <Plus className="h-5 w-5 text-emerald-600" />
            <h2 className="text-sm font-bold text-gray-900">Add Time Slot</h2>
          </div>
          <div className="space-y-4">
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-gray-700 uppercase tracking-widest">Day</label>
              <select value={newDay} onChange={(e) => setNewDay(e.target.value)} className="h-11 w-full px-4 rounded-xl border border-gray-200 text-sm font-medium bg-white focus:ring-2 focus:ring-emerald-500 outline-none">
                {DAYS.map((d) => <option key={d} value={d}>{d}</option>)}
              </select>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-700 uppercase tracking-widest">Start</label>
                <input type="time" value={newStart} onChange={(e) => setNewStart(e.target.value)} className="h-11 w-full px-4 rounded-xl border border-gray-200 text-sm font-medium bg-white focus:ring-2 focus:ring-emerald-500 outline-none" />
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-gray-700 uppercase tracking-widest">End</label>
                <input type="time" value={newEnd} onChange={(e) => setNewEnd(e.target.value)} className="h-11 w-full px-4 rounded-xl border border-gray-200 text-sm font-medium bg-white focus:ring-2 focus:ring-emerald-500 outline-none" />
              </div>
            </div>
            <Button onClick={handleAdd} className="w-full h-11 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold shadow-md">
              <Save className="h-4 w-4 mr-2" /> Save Time Slot
            </Button>
          </div>
        </div>
      </div>

      {/* Records Section */}
      <div className="bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden">
        <button onClick={() => setShowRecords(!showRecords)} className="w-full p-6 flex items-center justify-between hover:bg-gray-50/50 transition-colors">
          <div className="flex items-center gap-3">
            <Users className="h-5 w-5 text-blue-600" />
            <h2 className="text-sm font-bold text-gray-900">Visitor Records</h2>
            <span className="text-[10px] font-bold text-gray-400 bg-gray-50 px-2 py-1 rounded-full">{completedVisits.length} entries</span>
          </div>
          <ChevronDown className={`h-5 w-5 text-gray-400 transition-transform ${showRecords ? 'rotate-180' : ''}`} />
        </button>

        {showRecords && (
          <div className="p-6 pt-0 animate-in slide-in-from-top duration-200">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Filter:</label>
                <select value={filterRole} onChange={(e) => setFilterRole(e.target.value)} className="h-9 px-3 rounded-lg border border-gray-200 text-xs font-medium bg-white">
                  <option value="all">All Roles</option>
                  <option value="student">Students</option>
                  <option value="teacher">Teachers</option>
                  <option value="sa">Student Assistants</option>
                </select>
              </div>
              <Button variant="outline" size="sm" onClick={handlePrint} className="rounded-xl text-xs font-bold gap-1.5">
                <Printer className="h-3.5 w-3.5" /> Print Records
              </Button>
            </div>

            <div ref={printRef}>
              {filteredVisits.length === 0 ? (
                <p className="text-sm text-gray-400 text-center py-8">No completed visits yet.</p>
              ) : (
                <table className="w-full text-left">
                  <thead>
                    <tr className="text-[9px] font-bold tracking-widest text-gray-400 uppercase border-b border-gray-100">
                      <th className="pb-3">Name</th>
                      <th className="pb-3">Role</th>
                      <th className="pb-3">Date</th>
                      <th className="pb-3">Entered</th>
                      <th className="pb-3">Left</th>
                      <th className="pb-3 text-right">Duration</th>
                    </tr>
                  </thead>
                  <tbody className="text-xs font-medium text-gray-700 divide-y divide-gray-50">
                    {filteredVisits.map((v) => (
                      <tr key={v.id} className="hover:bg-gray-50/50">
                        <td className="py-3 font-bold">{v.userName}</td>
                        <td className="py-3 capitalize text-gray-500">{v.userRole}</td>
                        <td className="py-3 text-gray-500">{new Date(v.enteredAt).toLocaleDateString()}</td>
                        <td className="py-3 text-gray-500 font-mono text-[11px]">{new Date(v.enteredAt).toLocaleTimeString()}</td>
                        <td className="py-3 text-gray-500 font-mono text-[11px]">{v.leftAt ? new Date(v.leftAt).toLocaleTimeString() : '—'}</td>
                        <td className="py-3 text-right font-bold text-emerald-600">{v.duration != null ? `${v.duration} min` : '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
